#    Copyright 2016 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""eeee

Revision ID: 34079d7bf3e1
Revises: 1b1d4016375d
Create Date: 2016-05-31 15:31:38.614903

"""

# revision identifiers, used by Alembic.
revision = '34079d7bf3e1'
down_revision = '1b1d4016375d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cluster_deploy_msg', 'cluster_deploymsg',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('cluster_deploy_msg', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cluster_role_status', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cluster_setting_info', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cluster_setting_info', 'cluster_setting',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('clusters', 'cluster_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('physical_machine_info', 'additional_info',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('physical_machine_info', 'cabinet',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('physical_machine_info', 'gene_room',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('physical_machine_info', 'mp_ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('physical_machine_info', 'mp_passwd',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('releases', 'profilename',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('releases', 'profilename',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('physical_machine_info', 'mp_passwd',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('physical_machine_info', 'mp_ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('physical_machine_info', 'gene_room',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('physical_machine_info', 'cabinet',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('physical_machine_info', 'additional_info',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('clusters', 'cluster_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cluster_setting_info', 'cluster_setting',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('cluster_setting_info', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cluster_role_status', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cluster_deploy_msg', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cluster_deploy_msg', 'cluster_deploymsg',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###
